# Generated by Django 3.2.1 on 2021-06-13 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kosakata', '0003_alter_kosakata_arti_kata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kosakata',
            name='arti_kata',
        ),
    ]
